namespace Jaarplanner.Domain.Curriculum;

/// <summary>
/// One applied import of the Op.stap curriculum from KOV's API: which numbered snapshot it read and when it was applied
/// (E1-21, ADR-0032 decision 6). A dekkingscijfer can then name the curriculum version it was computed against, and a
/// later import can say which version it replaces.
/// <para>
/// <b>A history, not a single "current" row.</b> Each apply appends one; the current version is the most recent. Nothing
/// updates or deletes a row, for the same reason the import never deletes a goal: it is the record of what was done.
/// </para>
/// <para>
/// <b>What it does not say.</b> The discipline selection (<c>Opstap:DisciplineSelectie</c>) can leave a discipline out of
/// an apply, and that discipline then still holds whatever an earlier import wrote. The row records which snapshot an
/// apply read, not that every discipline in the database is at that version.
/// </para>
/// </summary>
public sealed class Opstapversie
{
    // EF Core materialisation only — not an application construction path.
    private Opstapversie()
    {
        Versie = null!;
        Hash = null!;
    }

    /// <summary>Records an applied import.</summary>
    /// <param name="versie">KOV's numbered snapshot version, e.g. <c>1.2</c>. Never <c>latest</c>.</param>
    /// <param name="hash">The hash KOV publishes for that version's <c>krcItems</c>.</param>
    /// <param name="toegepastOp">When the import was applied.</param>
    public Opstapversie(string versie, string hash, DateTimeOffset toegepastOp)
    {
        Versie = IsGeldigeVersie(versie)
            ? versie.Trim()
            : throw new ArgumentException($"'{versie}' is not a numbered Op.stap version such as 1.2.", nameof(versie));
        Hash = Require(hash, nameof(hash));
        ToegepastOp = toegepastOp;
    }

    /// <summary>
    /// True when <paramref name="versie"/> is a numbered snapshot version as KOV writes them (<c>1.2</c>): one to four
    /// dot-separated numbers. <c>latest</c> is deliberately not one (ADR-0032 decision 6), and because the value ends up
    /// in a request path, nothing but digits and dots may pass.
    /// </summary>
    public static bool IsGeldigeVersie(string? versie)
    {
        var waarde = versie?.Trim();
        if (string.IsNullOrEmpty(waarde) || waarde.Length > 16)
        {
            return false;
        }

        var delen = waarde.Split('.');
        return delen.Length <= 4 && delen.All(d => d.Length is > 0 and <= 3 && d.All(char.IsAsciiDigit));
    }

    /// <summary>Surrogate key, generated by the database.</summary>
    public int Id { get; private set; }

    /// <summary>KOV's numbered snapshot version, e.g. <c>1.2</c>.</summary>
    public string Versie { get; private set; }

    /// <summary>The hash KOV publishes for that version's <c>krcItems</c>.</summary>
    public string Hash { get; private set; }

    /// <summary>When the import was applied.</summary>
    public DateTimeOffset ToegepastOp { get; private set; }

    private static string Require(string value, string paramName)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException($"'{paramName}' is required.", paramName);
        }

        return value.Trim();
    }
}
