// <auto-generated />
using System;
using Jaarplanner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jaarplanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824134924_ActiviteitKleur")]
    partial class ActiviteitKleur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Discipline", b =>
                {
                    b.Property<string>("Nummer")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParentDisciplineNummer")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Nummer");

                    b.HasIndex("ParentDisciplineNummer");

                    b.ToTable("disciplines", (string)null);

                    b.HasData(
                        new
                        {
                            Nummer = "1",
                            Naam = "Nederlands en communicatie"
                        },
                        new
                        {
                            Nummer = "2",
                            Naam = "Wiskunde"
                        },
                        new
                        {
                            Nummer = "3",
                            Naam = "Wetenschap en techniek"
                        },
                        new
                        {
                            Nummer = "4",
                            Naam = "Aardrijkskunde"
                        },
                        new
                        {
                            Nummer = "5",
                            Naam = "Geschiedenis"
                        },
                        new
                        {
                            Nummer = "6",
                            Naam = "Muzische vorming"
                        },
                        new
                        {
                            Nummer = "7",
                            Naam = "Lichamelijke opvoeding en motoriek"
                        },
                        new
                        {
                            Nummer = "8",
                            Naam = "ICT"
                        },
                        new
                        {
                            Nummer = "9.1",
                            Naam = "Veilige en gezonde levensstijl"
                        },
                        new
                        {
                            Nummer = "9.2",
                            Naam = "Leren leren"
                        },
                        new
                        {
                            Nummer = "9.3",
                            Naam = "Sociaal en emotioneel leren"
                        },
                        new
                        {
                            Nummer = "10",
                            Naam = "Frans"
                        },
                        new
                        {
                            Nummer = "11",
                            Naam = "Rooms-katholieke godsdienst"
                        });
                });

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Leerplandoel", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Cluster")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DisciplineNummer")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Doelsoort")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("doelsoort");

                    b.Property<string>("Domein")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("JaarFase")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("MinimumdoelRef")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("NietMeerInOpstap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("niet_meer_in_opstap");

                    b.Property<string>("Subdomein")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Toelichting")
                        .HasColumnType("text");

                    b.Property<string>("Voorbeelden")
                        .HasColumnType("text");

                    b.Property<string>("Woordenschat")
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("DisciplineNummer");

                    b.HasIndex("MinimumdoelRef");

                    b.HasIndex("Domein", "Subdomein");

                    b.ToTable("leerplandoelen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Minimumdoel", b =>
                {
                    b.Property<string>("Ref")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Leeftijd")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Nr")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ref");

                    b.ToTable("minimumdoelen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Activiteitplaatsing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiviteitId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<Guid>("JaarplanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Volgorde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ActiviteitId");

                    b.HasIndex("JaarplanId", "Datum");

                    b.HasIndex("JaarplanId", "ActiviteitId", "Datum")
                        .IsUnique();

                    b.ToTable("activiteitplaatsingen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Generatieparameters", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KlasId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchooljaarId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchooljaarId");

                    b.HasIndex("KlasId", "SchooljaarId")
                        .IsUnique();

                    b.ToTable("generatieparameters", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Jaarplan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KlasId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KlasId")
                        .IsUnique();

                    b.ToTable("jaarplannen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Klas", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Leerjaar")
                        .HasColumnType("integer");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SchooljaarId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Naam")
                        .IsUnique();

                    b.HasIndex("SchooljaarId");

                    b.ToTable("klassen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Schooljaar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Eind")
                        .HasColumnType("date");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Naam")
                        .IsUnique();

                    b.ToTable("schooljaren", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Activiteit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActiviteitType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("activiteit_type");

                    b.Property<string>("Hoek")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Kleur")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kleur");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("OnderzoeksvraagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubthemaId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerwachteUitkomsten")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OnderzoeksvraagId");

                    b.HasIndex("SubthemaId");

                    b.ToTable("activiteiten", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Onderzoeksvraag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Probleemstelling")
                        .HasColumnType("text");

                    b.Property<Guid>("SubthemaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Vraag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubthemaId");

                    b.ToTable("onderzoeksvragen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subdoel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Leeftijd")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("SubthemaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubthemaId");

                    b.ToTable("subdoelen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subthema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DuurWeken")
                        .HasColumnType("integer");

                    b.Property<Guid>("KlasId")
                        .HasColumnType("uuid");

                    b.Property<string>("Leeftijd")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ThemaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ThemaId");

                    b.HasIndex("KlasId", "Leeftijd");

                    b.ToTable("subthemas", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Thema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DuurWeken")
                        .HasColumnType("integer");

                    b.Property<string>("Invalshoeken")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Kernwoordenschat")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<string[]>("RijkeWoordenschat")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("themas", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Themadoel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThemaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ThemaId");

                    b.ToTable("themadoelen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Discipline", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Curriculum.Discipline", null)
                        .WithMany()
                        .HasForeignKey("ParentDisciplineNummer")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Leerplandoel", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Curriculum.Discipline", null)
                        .WithMany()
                        .HasForeignKey("DisciplineNummer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Curriculum.Minimumdoel", null)
                        .WithMany()
                        .HasForeignKey("MinimumdoelRef")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Activiteitplaatsing", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Activiteit", null)
                        .WithMany()
                        .HasForeignKey("ActiviteitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Planning.Jaarplan", null)
                        .WithMany("_activiteitplaatsingen")
                        .HasForeignKey("JaarplanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Generatieparameters", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Planning.Klas", null)
                        .WithMany()
                        .HasForeignKey("KlasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Planning.Schooljaar", null)
                        .WithMany()
                        .HasForeignKey("SchooljaarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Jaarplanner.Domain.Planning.BewaardStartthema", "_startthemas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("BlokStart")
                                .HasColumnType("date");

                            b1.Property<Guid>("GeneratieparametersId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ThemaNaam")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("Id");

                            b1.HasIndex("GeneratieparametersId", "BlokStart")
                                .IsUnique();

                            b1.ToTable("startthemavoorkeuren", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GeneratieparametersId");
                        });

                    b.OwnsMany("Jaarplanner.Domain.Planning.BewaardVastMoment", "_vasteMomenten", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<bool>("BlokkeertPlaatsing")
                                .HasColumnType("boolean");

                            b1.Property<DateOnly>("Datum")
                                .HasColumnType("date");

                            b1.Property<Guid>("GeneratieparametersId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Naam")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("Id");

                            b1.HasIndex("GeneratieparametersId", "Datum");

                            b1.ToTable("vastemomenten", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GeneratieparametersId");
                        });

                    b.Navigation("_startthemas");

                    b.Navigation("_vasteMomenten");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Jaarplan", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Planning.Klas", null)
                        .WithMany()
                        .HasForeignKey("KlasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Jaarplanner.Domain.Planning.Themaplaatsing", "_plaatsingen", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("AiMotivatie")
                                .HasColumnType("text");

                            b1.Property<string>("BlokNiveau")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<DateOnly>("BlokStart")
                                .HasColumnType("date");

                            b1.Property<Guid>("JaarplanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<Guid>("ThemaId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Vergrendeld")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false);

                            b1.HasKey("Id");

                            b1.HasIndex("ThemaId");

                            b1.HasIndex("JaarplanId", "BlokStart");

                            b1.HasIndex("JaarplanId", "ThemaId", "BlokNiveau", "BlokStart")
                                .IsUnique();

                            b1.ToTable("themaplaatsingen", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JaarplanId");

                            b1.HasOne("Jaarplanner.Domain.Schoolcontent.Thema", null)
                                .WithMany()
                                .HasForeignKey("ThemaId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("_plaatsingen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Klas", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Planning.Schooljaar", null)
                        .WithMany("_klassen")
                        .HasForeignKey("SchooljaarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Schooljaar", b =>
                {
                    b.OwnsMany("Jaarplanner.Domain.Planning.Schoolsluiting", "_sluitingen", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Eind")
                                .HasColumnType("date");

                            b1.Property<string>("Naam")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<Guid>("SchooljaarId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Soort")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date");

                            b1.HasKey("Id");

                            b1.HasIndex("SchooljaarId", "Start");

                            b1.ToTable("schoolsluitingen", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SchooljaarId");
                        });

                    b.Navigation("_sluitingen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Activiteit", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Onderzoeksvraag", null)
                        .WithMany()
                        .HasForeignKey("OnderzoeksvraagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Subthema", null)
                        .WithMany("Activiteiten")
                        .HasForeignKey("SubthemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Jaarplanner.Domain.Schoolcontent.DoelKoppeling", "Doelkoppelingen", b1 =>
                        {
                            b1.Property<Guid>("ActiviteitId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("AiMotivatie")
                                .HasColumnType("text")
                                .HasColumnName("ai_motivatie");

                            b1.Property<string>("LeerplandoelCode")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("leerplandoel_code");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.HasKey("ActiviteitId", "Id");

                            b1.HasIndex("LeerplandoelCode");

                            b1.ToTable("activiteiten_Doelkoppelingen");

                            b1.WithOwner()
                                .HasForeignKey("ActiviteitId");

                            b1.HasOne("Jaarplanner.Domain.Curriculum.Leerplandoel", null)
                                .WithMany()
                                .HasForeignKey("LeerplandoelCode")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("Doelkoppelingen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Onderzoeksvraag", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Subthema", null)
                        .WithMany("Onderzoeksvragen")
                        .HasForeignKey("SubthemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subdoel", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Subthema", null)
                        .WithMany("Subdoelen")
                        .HasForeignKey("SubthemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Jaarplanner.Domain.Schoolcontent.DoelKoppeling", "Koppeling", b1 =>
                        {
                            b1.Property<Guid>("SubdoelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AiMotivatie")
                                .HasColumnType("text")
                                .HasColumnName("ai_motivatie");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("LeerplandoelCode")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("leerplandoel_code");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.HasKey("SubdoelId");

                            b1.HasIndex("LeerplandoelCode");

                            b1.ToTable("subdoelen");

                            b1.HasOne("Jaarplanner.Domain.Curriculum.Leerplandoel", null)
                                .WithMany()
                                .HasForeignKey("LeerplandoelCode")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("SubdoelId");
                        });

                    b.Navigation("Koppeling")
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subthema", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Planning.Klas", null)
                        .WithMany()
                        .HasForeignKey("KlasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Thema", null)
                        .WithMany("Subthemas")
                        .HasForeignKey("ThemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Thema", b =>
                {
                    b.OwnsMany("Jaarplanner.Domain.Schoolcontent.DoelKoppeling", "Doelsuggesties", b1 =>
                        {
                            b1.Property<Guid>("ThemaId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("AiMotivatie")
                                .HasColumnType("text")
                                .HasColumnName("ai_motivatie");

                            b1.Property<string>("LeerplandoelCode")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("leerplandoel_code");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.HasKey("ThemaId", "Id");

                            b1.HasIndex("LeerplandoelCode");

                            b1.ToTable("thema_doelsuggesties", (string)null);

                            b1.HasOne("Jaarplanner.Domain.Curriculum.Leerplandoel", null)
                                .WithMany()
                                .HasForeignKey("LeerplandoelCode")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ThemaId");
                        });

                    b.Navigation("Doelsuggesties");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Themadoel", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Thema", null)
                        .WithMany("Themadoelen")
                        .HasForeignKey("ThemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Jaarplanner.Domain.Schoolcontent.DoelKoppeling", "Koppeling", b1 =>
                        {
                            b1.Property<Guid>("ThemadoelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AiMotivatie")
                                .HasColumnType("text")
                                .HasColumnName("ai_motivatie");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("LeerplandoelCode")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("leerplandoel_code");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.HasKey("ThemadoelId");

                            b1.HasIndex("LeerplandoelCode");

                            b1.ToTable("themadoelen");

                            b1.HasOne("Jaarplanner.Domain.Curriculum.Leerplandoel", null)
                                .WithMany()
                                .HasForeignKey("LeerplandoelCode")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ThemadoelId");
                        });

                    b.Navigation("Koppeling")
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Jaarplan", b =>
                {
                    b.Navigation("_activiteitplaatsingen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Schooljaar", b =>
                {
                    b.Navigation("_klassen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subthema", b =>
                {
                    b.Navigation("Activiteiten");

                    b.Navigation("Onderzoeksvragen");

                    b.Navigation("Subdoelen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Thema", b =>
                {
                    b.Navigation("Subthemas");

                    b.Navigation("Themadoelen");
                });
#pragma warning restore 612, 618
        }
    }
}
