// <auto-generated />
using Jaarplanner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jaarplanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630073510_CurriculumReadOnlyEntities")]
    partial class CurriculumReadOnlyEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Discipline", b =>
                {
                    b.Property<string>("Nummer")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParentDisciplineNummer")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Nummer");

                    b.HasIndex("ParentDisciplineNummer");

                    b.ToTable("disciplines", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Leerplandoel", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Cluster")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DisciplineNummer")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Doelsoort")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("doelsoort");

                    b.Property<string>("Domein")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("JaarFase")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("MinimumdoelRef")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Subdomein")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Toelichting")
                        .HasColumnType("text");

                    b.Property<string>("Voorbeelden")
                        .HasColumnType("text");

                    b.Property<string>("Woordenschat")
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("DisciplineNummer");

                    b.HasIndex("MinimumdoelRef");

                    b.HasIndex("Domein", "Subdomein");

                    b.ToTable("leerplandoelen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Minimumdoel", b =>
                {
                    b.Property<string>("Ref")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Leeftijd")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Nr")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ref");

                    b.ToTable("minimumdoelen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Discipline", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Curriculum.Discipline", null)
                        .WithMany()
                        .HasForeignKey("ParentDisciplineNummer")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Leerplandoel", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Curriculum.Discipline", null)
                        .WithMany()
                        .HasForeignKey("DisciplineNummer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Curriculum.Minimumdoel", null)
                        .WithMany()
                        .HasForeignKey("MinimumdoelRef")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
