// <auto-generated />
using System;
using Jaarplanner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jaarplanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Discipline", b =>
                {
                    b.Property<string>("Nummer")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParentDisciplineNummer")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Nummer");

                    b.HasIndex("ParentDisciplineNummer");

                    b.ToTable("disciplines", (string)null);

                    b.HasData(
                        new
                        {
                            Nummer = "1",
                            Naam = "Nederlands en communicatie"
                        },
                        new
                        {
                            Nummer = "2",
                            Naam = "Wiskunde"
                        },
                        new
                        {
                            Nummer = "3",
                            Naam = "Wetenschap en techniek"
                        },
                        new
                        {
                            Nummer = "4",
                            Naam = "Aardrijkskunde"
                        },
                        new
                        {
                            Nummer = "5",
                            Naam = "Geschiedenis"
                        },
                        new
                        {
                            Nummer = "6",
                            Naam = "Muzische vorming"
                        },
                        new
                        {
                            Nummer = "7",
                            Naam = "Lichamelijke opvoeding en motoriek"
                        },
                        new
                        {
                            Nummer = "8",
                            Naam = "ICT"
                        },
                        new
                        {
                            Nummer = "9.1",
                            Naam = "Veilige en gezonde levensstijl"
                        },
                        new
                        {
                            Nummer = "9.2",
                            Naam = "Leren leren"
                        },
                        new
                        {
                            Nummer = "9.3",
                            Naam = "Sociaal en emotioneel leren"
                        },
                        new
                        {
                            Nummer = "10",
                            Naam = "Frans"
                        },
                        new
                        {
                            Nummer = "11",
                            Naam = "Rooms-katholieke godsdienst"
                        });
                });

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Leerplandoel", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Cluster")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DisciplineNummer")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Doelsoort")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("doelsoort");

                    b.Property<string>("Domein")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("JaarFase")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("MinimumdoelRef")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("NietMeerInOpstap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("niet_meer_in_opstap");

                    b.Property<Guid?>("OpstapSleutel")
                        .HasColumnType("uuid")
                        .HasColumnName("opstap_sleutel");

                    b.Property<string>("Subdomein")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Toelichting")
                        .HasColumnType("text");

                    b.Property<string>("Voorbeelden")
                        .HasColumnType("text");

                    b.Property<string>("Woordenschat")
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("DisciplineNummer");

                    b.HasIndex("MinimumdoelRef");

                    b.HasIndex("OpstapSleutel");

                    b.HasIndex("Domein", "Subdomein");

                    b.ToTable("leerplandoelen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Minimumdoel", b =>
                {
                    b.Property<string>("Ref")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Leeftijd")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Leergebied")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("leergebied");

                    b.Property<bool>("NietMeerInOpstap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("niet_meer_in_opstap");

                    b.Property<string>("Nr")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rubriek")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("rubriek");

                    b.Property<string>("Soort")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("soort");

                    b.Property<string>("Subrubriek")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subrubriek");

                    b.Property<string>("ZonderLeerplandoelDoelsets")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("zonder_leerplandoel_doelsets");

                    b.Property<string>("ZonderLeerplandoelReden")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("zonder_leerplandoel_reden");

                    b.HasKey("Ref");

                    b.ToTable("minimumdoelen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Opstapversie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ToegepastOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Versie")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ToegepastOp");

                    b.ToTable("opstapversies", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.Gradatie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Kleur")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Volgorde")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("gradaties", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.Kindtekening", b =>
                {
                    b.Property<Guid>("OntwikkelingsrapportId")
                        .HasColumnType("uuid");

                    b.Property<int>("Breedte")
                        .HasColumnType("integer");

                    b.Property<string>("Formaat")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Hoogte")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Inhoud")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("Versie")
                        .HasColumnType("uuid");

                    b.HasKey("OntwikkelingsrapportId");

                    b.ToTable("kindtekeningen", null, t =>
                        {
                            t.HasCheckConstraint("CK_kindtekeningen_Breedte", "\"Breedte\" > 0");

                            t.HasCheckConstraint("CK_kindtekeningen_Hoogte", "\"Hoogte\" > 0");
                        });
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.Leerling", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("KlasId")
                        .HasColumnType("uuid");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("KlasId");

                    b.ToTable("leerlingen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.Ontwikkelingsrapport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Besluit")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("BesluitHerschrijvingGeweigerd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("BesluitStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("LeerlingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Moment")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeerlingId", "Moment")
                        .IsUnique();

                    b.ToTable("ontwikkelingsrapporten", null, t =>
                        {
                            t.HasCheckConstraint("CK_ontwikkelingsrapporten_Moment", "\"Moment\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.Rapportbeoordeling", b =>
                {
                    b.Property<Guid>("OntwikkelingsrapportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RapportdoelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GradatieId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HerschrijvingGeweigerd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Tekst")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TekstStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("OntwikkelingsrapportId", "RapportdoelId");

                    b.HasIndex("GradatieId");

                    b.HasIndex("RapportdoelId");

                    b.ToTable("rapportbeoordelingen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.Rapportdoel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Volgorde")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("rapportdoelen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.RapportdoelSubdoel", b =>
                {
                    b.Property<Guid>("RapportdoelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubdoelId")
                        .HasColumnType("uuid");

                    b.HasKey("RapportdoelId", "SubdoelId");

                    b.HasIndex("SubdoelId");

                    b.ToTable("rapportdoel_subdoelen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Activiteitplaatsing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiviteitId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("Begin")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Einde")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("JaarplanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ActiviteitId");

                    b.HasIndex("JaarplanId", "Datum");

                    b.HasIndex("JaarplanId", "ActiviteitId", "Datum", "Begin")
                        .IsUnique();

                    b.ToTable("activiteitplaatsingen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.AlgemeneFichemoment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("Begin")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Einde")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("PlaatsingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tekst")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PlaatsingId");

                    b.HasIndex("Datum", "Begin");

                    b.ToTable("algemene_fichemomenten", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.AlgemeneFicheplaatsing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlgemeneFicheId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KlasId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Tot")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Van")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AlgemeneFicheId");

                    b.HasIndex("KlasId", "Van", "Tot");

                    b.ToTable("algemene_ficheplaatsingen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Generatieparameters", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KlasId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchooljaarId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchooljaarId");

                    b.HasIndex("KlasId", "SchooljaarId")
                        .IsUnique();

                    b.ToTable("generatieparameters", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Hoekmoment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("Begin")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Einde")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("HoekplaatsingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HoekplaatsingId");

                    b.HasIndex("Datum", "Begin");

                    b.ToTable("hoekmomenten", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Hoekplaatsing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HoekId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KlasId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Tot")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Van")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HoekId");

                    b.HasIndex("KlasId", "Van", "Tot");

                    b.ToTable("hoekplaatsingen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Hoekverrijking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HoekId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubthemaplaatsingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubthemaplaatsingId");

                    b.HasIndex("HoekId", "SubthemaplaatsingId")
                        .IsUnique();

                    b.ToTable("hoekverrijkingen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Jaarplan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KlasId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KlasId")
                        .IsUnique();

                    b.ToTable("jaarplannen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Klas", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Jaarfase")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Leerjaar")
                        .HasColumnType("integer");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SchooljaarId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Naam")
                        .IsUnique();

                    b.HasIndex("SchooljaarId");

                    b.ToTable("klassen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Schooldaguren", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("Begin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Einde")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("MiddagpauzeBegin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("MiddagpauzeEinde")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Weekdag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Weekdag")
                        .IsUnique();

                    b.ToTable("schooldaguren", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Schooljaar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Eind")
                        .HasColumnType("date");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Naam")
                        .IsUnique();

                    b.ToTable("schooljaren", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Subthemaplaatsing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JaarplanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubthemaId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Tot")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Van")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SubthemaId");

                    b.HasIndex("JaarplanId", "SubthemaId", "Van")
                        .IsUnique();

                    b.HasIndex("JaarplanId", "Van", "Tot");

                    b.ToTable("subthemaplaatsingen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Activiteit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActiviteitType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("activiteit_type");

                    b.Property<Guid?>("EigenaarId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hoek")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Kleur")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kleur");

                    b.Property<int>("LengteInLesuren")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("lengte_in_lesuren");

                    b.Property<Guid?>("MakerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("OnderzoeksvraagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubthemaId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerwachteUitkomsten")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.HasIndex("MakerId");

                    b.HasIndex("OnderzoeksvraagId");

                    b.HasIndex("SubthemaId");

                    b.ToTable("activiteiten", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Activiteitvoorstel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiviteitId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActiviteitType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AiMotivatie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GebruikerId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("LeerplandoelCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("LengteInLesuren")
                        .HasColumnType("integer");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OnderzoeksvraagId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SubthemaId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerwachteUitkomsten")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Volgnummer")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ActiviteitId");

                    b.HasIndex("GebruikerId");

                    b.HasIndex("OnderzoeksvraagId");

                    b.HasIndex("SubthemaId", "GebruikerId");

                    b.ToTable("activiteitvoorstellen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.AlgemeneFiche", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KlasId")
                        .HasColumnType("uuid");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KlasId", "Naam")
                        .IsUnique();

                    b.ToTable("algemene_fiches", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Hoek", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KlasId")
                        .HasColumnType("uuid");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KlasId", "Naam")
                        .IsUnique();

                    b.ToTable("hoeken", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Onderzoeksvraag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Probleemstelling")
                        .HasColumnType("text");

                    b.Property<Guid>("SubthemaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Vraag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubthemaId");

                    b.ToTable("onderzoeksvragen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subdoel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Leeftijd")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("SubthemaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubthemaId");

                    b.ToTable("subdoelen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subdoelvoorstel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AiMotivatie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Leeftijd")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("LeerplandoelCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("leerplandoel_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("SubthemaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubthemavoorstelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThemaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeerplandoelCode");

                    b.HasIndex("SubthemaId");

                    b.HasIndex("SubthemavoorstelId");

                    b.HasIndex("ThemaId", "Leeftijd");

                    b.ToTable("subdoelvoorstellen", null, t =>
                        {
                            t.HasCheckConstraint("CK_subdoelvoorstellen_EenBestemming", "(\"SubthemaId\" IS NULL) <> (\"SubthemavoorstelId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subthema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DuurWeken")
                        .HasColumnType("integer");

                    b.Property<string>("Leeftijd")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ThemaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Leeftijd");

                    b.HasIndex("ThemaId");

                    b.ToTable("subthemas", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subthemavoorstel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AiMotivatie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DuurWeken")
                        .HasColumnType("integer");

                    b.Property<string>("Leeftijd")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Onderzoeksvraag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("SubthemaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThemaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubthemaId");

                    b.HasIndex("ThemaId", "Leeftijd");

                    b.ToTable("subthemavoorstellen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Thema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DuurWeken")
                        .HasColumnType("integer");

                    b.Property<string>("Invalshoeken")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Kernwoordenschat")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<string[]>("RijkeWoordenschat")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("themas", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.ThemaMinimumdoel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("MinimumdoelRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("minimumdoel_ref");

                    b.Property<Guid>("ThemaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MinimumdoelRef");

                    b.HasIndex("ThemaId", "MinimumdoelRef")
                        .IsUnique();

                    b.ToTable("thema_minimumdoelen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Themadoel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThemaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ThemaId");

                    b.ToTable("themadoelen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Wizardrun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AfgerondOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("GeslotenOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GestartDoorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GestartOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LaatsteSchrijfactieOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ThemaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GestartDoorId");

                    b.HasIndex("ThemaId")
                        .IsUnique();

                    b.ToTable("wizardruns", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Woordweb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubthemaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.HasIndex("SubthemaId", "EigenaarId")
                        .IsUnique();

                    b.ToTable("woordwebs", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.WoordwebWoord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AiMotivatie")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Volgnummer")
                        .HasColumnType("integer");

                    b.Property<string>("Woord")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("WoordwebId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WoordwebId");

                    b.ToTable("woordweb_woorden", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Toegang.Gebruiker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("EntraObjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntraTenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HeeftLeerlingzorg")
                        .HasColumnType("boolean");

                    b.Property<bool>("HeeftThemabeheer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDirectie")
                        .HasColumnType("boolean");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EntraTenantId", "EntraObjectId")
                        .IsUnique();

                    b.ToTable("gebruikers", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Toegang.Hoofdleerkrachtaanstelling", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GebruikerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Jaarfase")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("SchooljaarId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchooljaarId", "Jaarfase");

                    b.HasIndex("GebruikerId", "SchooljaarId", "Jaarfase")
                        .IsUnique();

                    b.ToTable("hoofdleerkrachtaanstellingen", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Toegang.Klastoewijzing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GebruikerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KlasId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KlasId");

                    b.HasIndex("GebruikerId", "KlasId")
                        .IsUnique();

                    b.ToTable("klastoewijzingen", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Discipline", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Curriculum.Discipline", null)
                        .WithMany()
                        .HasForeignKey("ParentDisciplineNummer")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Curriculum.Leerplandoel", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Curriculum.Discipline", null)
                        .WithMany()
                        .HasForeignKey("DisciplineNummer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Curriculum.Minimumdoel", null)
                        .WithMany()
                        .HasForeignKey("MinimumdoelRef")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.Kindtekening", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Ontwikkelingsrapport.Ontwikkelingsrapport", null)
                        .WithOne()
                        .HasForeignKey("Jaarplanner.Domain.Ontwikkelingsrapport.Kindtekening", "OntwikkelingsrapportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.Leerling", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Planning.Klas", null)
                        .WithMany()
                        .HasForeignKey("KlasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.Ontwikkelingsrapport", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Ontwikkelingsrapport.Leerling", null)
                        .WithMany()
                        .HasForeignKey("LeerlingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.Rapportbeoordeling", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Ontwikkelingsrapport.Gradatie", null)
                        .WithMany()
                        .HasForeignKey("GradatieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jaarplanner.Domain.Ontwikkelingsrapport.Ontwikkelingsrapport", null)
                        .WithMany("Beoordelingen")
                        .HasForeignKey("OntwikkelingsrapportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Ontwikkelingsrapport.Rapportdoel", null)
                        .WithMany()
                        .HasForeignKey("RapportdoelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.RapportdoelSubdoel", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Ontwikkelingsrapport.Rapportdoel", null)
                        .WithMany("Subdoelen")
                        .HasForeignKey("RapportdoelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Subdoel", null)
                        .WithMany()
                        .HasForeignKey("SubdoelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Activiteitplaatsing", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Activiteit", null)
                        .WithMany()
                        .HasForeignKey("ActiviteitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Planning.Jaarplan", null)
                        .WithMany("_activiteitplaatsingen")
                        .HasForeignKey("JaarplanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.AlgemeneFichemoment", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Planning.AlgemeneFicheplaatsing", null)
                        .WithMany("Momenten")
                        .HasForeignKey("PlaatsingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.AlgemeneFicheplaatsing", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.AlgemeneFiche", null)
                        .WithMany()
                        .HasForeignKey("AlgemeneFicheId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Planning.Klas", null)
                        .WithMany()
                        .HasForeignKey("KlasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Generatieparameters", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Planning.Klas", null)
                        .WithMany()
                        .HasForeignKey("KlasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Planning.Schooljaar", null)
                        .WithMany()
                        .HasForeignKey("SchooljaarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Jaarplanner.Domain.Planning.BewaardStartthema", "_startthemas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("BlokStart")
                                .HasColumnType("date");

                            b1.Property<Guid>("GeneratieparametersId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ThemaNaam")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("Id");

                            b1.HasIndex("GeneratieparametersId", "BlokStart")
                                .IsUnique();

                            b1.ToTable("startthemavoorkeuren", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GeneratieparametersId");
                        });

                    b.OwnsMany("Jaarplanner.Domain.Planning.BewaardVastMoment", "_vasteMomenten", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<bool>("BlokkeertPlaatsing")
                                .HasColumnType("boolean");

                            b1.Property<DateOnly>("Datum")
                                .HasColumnType("date");

                            b1.Property<Guid>("GeneratieparametersId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Naam")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("Id");

                            b1.HasIndex("GeneratieparametersId", "Datum");

                            b1.ToTable("vastemomenten", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GeneratieparametersId");
                        });

                    b.Navigation("_startthemas");

                    b.Navigation("_vasteMomenten");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Hoekmoment", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Planning.Hoekplaatsing", null)
                        .WithMany("Momenten")
                        .HasForeignKey("HoekplaatsingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Hoekplaatsing", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Hoek", null)
                        .WithMany()
                        .HasForeignKey("HoekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Planning.Klas", null)
                        .WithMany()
                        .HasForeignKey("KlasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Hoekverrijking", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Hoek", null)
                        .WithMany()
                        .HasForeignKey("HoekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Planning.Subthemaplaatsing", null)
                        .WithMany()
                        .HasForeignKey("SubthemaplaatsingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Jaarplan", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Planning.Klas", null)
                        .WithMany()
                        .HasForeignKey("KlasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Jaarplanner.Domain.Planning.Themaplaatsing", "_plaatsingen", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("AiMotivatie")
                                .HasColumnType("text");

                            b1.Property<string>("BlokNiveau")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<DateOnly>("BlokStart")
                                .HasColumnType("date");

                            b1.Property<Guid>("JaarplanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<Guid>("ThemaId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Vergrendeld")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false);

                            b1.HasKey("Id");

                            b1.HasIndex("ThemaId");

                            b1.HasIndex("JaarplanId", "BlokStart");

                            b1.HasIndex("JaarplanId", "ThemaId", "BlokNiveau", "BlokStart")
                                .IsUnique();

                            b1.ToTable("themaplaatsingen", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JaarplanId");

                            b1.HasOne("Jaarplanner.Domain.Schoolcontent.Thema", null)
                                .WithMany()
                                .HasForeignKey("ThemaId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("_plaatsingen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Klas", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Planning.Schooljaar", null)
                        .WithMany("_klassen")
                        .HasForeignKey("SchooljaarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Schooljaar", b =>
                {
                    b.OwnsMany("Jaarplanner.Domain.Planning.Schoolsluiting", "_sluitingen", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Eind")
                                .HasColumnType("date");

                            b1.Property<string>("Naam")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<Guid>("SchooljaarId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Soort")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date");

                            b1.HasKey("Id");

                            b1.HasIndex("SchooljaarId", "Start");

                            b1.ToTable("schoolsluitingen", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SchooljaarId");
                        });

                    b.Navigation("_sluitingen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Subthemaplaatsing", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Planning.Jaarplan", null)
                        .WithMany("_subthemaplaatsingen")
                        .HasForeignKey("JaarplanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Subthema", null)
                        .WithMany()
                        .HasForeignKey("SubthemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Activiteit", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Toegang.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jaarplanner.Domain.Toegang.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("MakerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Onderzoeksvraag", null)
                        .WithMany()
                        .HasForeignKey("OnderzoeksvraagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Subthema", null)
                        .WithMany("Activiteiten")
                        .HasForeignKey("SubthemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Jaarplanner.Domain.Schoolcontent.DoelKoppeling", "Doelkoppelingen", b1 =>
                        {
                            b1.Property<Guid>("ActiviteitId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("AiMotivatie")
                                .HasColumnType("text")
                                .HasColumnName("ai_motivatie");

                            b1.Property<string>("LeerplandoelCode")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("leerplandoel_code");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.HasKey("ActiviteitId", "Id");

                            b1.HasIndex("LeerplandoelCode");

                            b1.ToTable("activiteiten_Doelkoppelingen");

                            b1.WithOwner()
                                .HasForeignKey("ActiviteitId");

                            b1.HasOne("Jaarplanner.Domain.Curriculum.Leerplandoel", null)
                                .WithMany()
                                .HasForeignKey("LeerplandoelCode")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("Doelkoppelingen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Activiteitvoorstel", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Activiteit", null)
                        .WithMany()
                        .HasForeignKey("ActiviteitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jaarplanner.Domain.Toegang.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Onderzoeksvraag", null)
                        .WithMany()
                        .HasForeignKey("OnderzoeksvraagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Subthema", null)
                        .WithMany()
                        .HasForeignKey("SubthemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.AlgemeneFiche", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Planning.Klas", null)
                        .WithMany()
                        .HasForeignKey("KlasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Jaarplanner.Domain.Schoolcontent.DoelKoppeling", "Doelkoppelingen", b1 =>
                        {
                            b1.Property<Guid>("AlgemeneFicheId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("AiMotivatie")
                                .HasColumnType("text")
                                .HasColumnName("ai_motivatie");

                            b1.Property<string>("LeerplandoelCode")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("leerplandoel_code");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.HasKey("AlgemeneFicheId", "Id");

                            b1.HasIndex("LeerplandoelCode");

                            b1.ToTable("algemene_fiche_doelkoppelingen", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AlgemeneFicheId");

                            b1.HasOne("Jaarplanner.Domain.Curriculum.Leerplandoel", null)
                                .WithMany()
                                .HasForeignKey("LeerplandoelCode")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("Doelkoppelingen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Hoek", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Planning.Klas", null)
                        .WithMany()
                        .HasForeignKey("KlasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Onderzoeksvraag", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Subthema", null)
                        .WithMany("Onderzoeksvragen")
                        .HasForeignKey("SubthemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subdoel", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Subthema", null)
                        .WithMany("Subdoelen")
                        .HasForeignKey("SubthemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Jaarplanner.Domain.Schoolcontent.DoelKoppeling", "Koppeling", b1 =>
                        {
                            b1.Property<Guid>("SubdoelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AiMotivatie")
                                .HasColumnType("text")
                                .HasColumnName("ai_motivatie");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("LeerplandoelCode")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("leerplandoel_code");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.HasKey("SubdoelId");

                            b1.HasIndex("LeerplandoelCode");

                            b1.ToTable("subdoelen");

                            b1.HasOne("Jaarplanner.Domain.Curriculum.Leerplandoel", null)
                                .WithMany()
                                .HasForeignKey("LeerplandoelCode")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("SubdoelId");
                        });

                    b.Navigation("Koppeling")
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subdoelvoorstel", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Curriculum.Leerplandoel", null)
                        .WithMany()
                        .HasForeignKey("LeerplandoelCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Subthema", null)
                        .WithMany()
                        .HasForeignKey("SubthemaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Subthemavoorstel", null)
                        .WithMany()
                        .HasForeignKey("SubthemavoorstelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Thema", null)
                        .WithMany()
                        .HasForeignKey("ThemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subthema", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Thema", null)
                        .WithMany("Subthemas")
                        .HasForeignKey("ThemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subthemavoorstel", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Subthema", null)
                        .WithMany()
                        .HasForeignKey("SubthemaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Thema", null)
                        .WithMany()
                        .HasForeignKey("ThemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Thema", b =>
                {
                    b.OwnsMany("Jaarplanner.Domain.Schoolcontent.DoelKoppeling", "Doelsuggesties", b1 =>
                        {
                            b1.Property<Guid>("ThemaId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("AiMotivatie")
                                .HasColumnType("text")
                                .HasColumnName("ai_motivatie");

                            b1.Property<string>("LeerplandoelCode")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("leerplandoel_code");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.HasKey("ThemaId", "Id");

                            b1.HasIndex("LeerplandoelCode");

                            b1.ToTable("thema_doelsuggesties", (string)null);

                            b1.HasOne("Jaarplanner.Domain.Curriculum.Leerplandoel", null)
                                .WithMany()
                                .HasForeignKey("LeerplandoelCode")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ThemaId");
                        });

                    b.Navigation("Doelsuggesties");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.ThemaMinimumdoel", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Curriculum.Minimumdoel", null)
                        .WithMany()
                        .HasForeignKey("MinimumdoelRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Thema", null)
                        .WithMany("Minimumdoelen")
                        .HasForeignKey("ThemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Themadoel", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Thema", null)
                        .WithMany("Themadoelen")
                        .HasForeignKey("ThemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Jaarplanner.Domain.Schoolcontent.DoelKoppeling", "Koppeling", b1 =>
                        {
                            b1.Property<Guid>("ThemadoelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AiMotivatie")
                                .HasColumnType("text")
                                .HasColumnName("ai_motivatie");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("LeerplandoelCode")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("leerplandoel_code");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.HasKey("ThemadoelId");

                            b1.HasIndex("LeerplandoelCode");

                            b1.ToTable("themadoelen");

                            b1.HasOne("Jaarplanner.Domain.Curriculum.Leerplandoel", null)
                                .WithMany()
                                .HasForeignKey("LeerplandoelCode")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ThemadoelId");
                        });

                    b.Navigation("Koppeling")
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Wizardrun", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Toegang.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("GestartDoorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Thema", null)
                        .WithMany()
                        .HasForeignKey("ThemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Jaarplanner.Domain.Schoolcontent.Wizardrunitem", "Aangemaakt", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Soort")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<Guid>("WizardrunId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WizardrunId", "ItemId")
                                .IsUnique();

                            b1.ToTable("wizardrunitems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WizardrunId");
                        });

                    b.Navigation("Aangemaakt");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Woordweb", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Toegang.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Subthema", null)
                        .WithMany()
                        .HasForeignKey("SubthemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.WoordwebWoord", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Schoolcontent.Woordweb", null)
                        .WithMany("Woorden")
                        .HasForeignKey("WoordwebId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Toegang.Hoofdleerkrachtaanstelling", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Toegang.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Planning.Schooljaar", null)
                        .WithMany()
                        .HasForeignKey("SchooljaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Toegang.Klastoewijzing", b =>
                {
                    b.HasOne("Jaarplanner.Domain.Toegang.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jaarplanner.Domain.Planning.Klas", null)
                        .WithMany()
                        .HasForeignKey("KlasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.Ontwikkelingsrapport", b =>
                {
                    b.Navigation("Beoordelingen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Ontwikkelingsrapport.Rapportdoel", b =>
                {
                    b.Navigation("Subdoelen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.AlgemeneFicheplaatsing", b =>
                {
                    b.Navigation("Momenten");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Hoekplaatsing", b =>
                {
                    b.Navigation("Momenten");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Jaarplan", b =>
                {
                    b.Navigation("_activiteitplaatsingen");

                    b.Navigation("_subthemaplaatsingen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Planning.Schooljaar", b =>
                {
                    b.Navigation("_klassen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Subthema", b =>
                {
                    b.Navigation("Activiteiten");

                    b.Navigation("Onderzoeksvragen");

                    b.Navigation("Subdoelen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Thema", b =>
                {
                    b.Navigation("Minimumdoelen");

                    b.Navigation("Subthemas");

                    b.Navigation("Themadoelen");
                });

            modelBuilder.Entity("Jaarplanner.Domain.Schoolcontent.Woordweb", b =>
                {
                    b.Navigation("Woorden");
                });
#pragma warning restore 612, 618
        }
    }
}
